# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0003_auto_20151220_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='gplus_author',
            field=models.CharField(blank=True, default='', help_text='Use the Google+ Name (together with "+")', max_length=255, verbose_name='Author Google+ URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='gplus_type',
            field=models.CharField(blank=True, choices=[('Article', 'Article'), ('Blog', 'Blog'), ('Book', 'Book'), ('Event', 'Event'), ('LocalBusiness', 'LocalBusiness'), ('Organization', 'Organization'), ('Person', 'Person'), ('Product', 'Product'), ('Review', 'Review')], help_text='Use Article for generic pages.', max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_author_fbid',
            field=models.CharField(blank=True, default='', help_text='Use Facebook numeric ID.', max_length=16, verbose_name='Author Facebook ID'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_author_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Author Facebook URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_publisher',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Website Facebook URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('website', 'Website')], help_text='Use Article for generic pages.', max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='twitter_type',
            field=models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary large image'), ('product', 'Product'), ('photo', 'Photo'), ('player', 'Player'), ('app', 'App')], max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='gplus_description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Google+ Description'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Facebook Description'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='twitter_description',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Twitter Description'),
        ),
    ]
