# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models

from meta import settings


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0003_auto_20151220_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='gplus_author',
            field=models.CharField(blank=True, default='', help_text='Use the Google+ Name (together with "+")', max_length=255, verbose_name='Author Google+ URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='gplus_type',
            field=models.CharField(blank=True, choices=settings.GPLUS_TYPES, help_text='Use Article for generic pages.', max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_author_fbid',
            field=models.CharField(blank=True, default='', help_text='Use Facebook numeric ID.', max_length=16, verbose_name='Author Facebook ID'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_author_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Author Facebook URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_publisher',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Website Facebook URL'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_type',
            field=models.CharField(blank=True, choices=settings.FB_TYPES, help_text='Use Article for generic pages.', max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='twitter_type',
            field=models.CharField(blank=True, choices=settings.TWITTER_TYPES, max_length=255, verbose_name='Resource type'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='gplus_description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Google+ Description'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Facebook Description'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='twitter_description',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Twitter Description'),
        ),
    ]
