# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0004_auto_20160409_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemeta',
            name='fb_pages',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook Pages ID'),
        ),
    ]
