# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0005_pagemeta_fb_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMetaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(default='name', max_length=200, verbose_name='attribute')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('value', models.CharField(max_length=2000, verbose_name='value')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='djangocms_page_meta.PageMeta')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='djangocms_page_meta.TitleMeta')),
            ],
            options={
                'verbose_name': 'Page meta info (language-dependent)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='genericmetaattribute',
            unique_together=set([('title', 'attribute', 'name', 'value'), ('page', 'attribute', 'name', 'value')]),
        ),
    ]
