# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0006_auto_20160423_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericmetaattribute',
            options={'verbose_name': 'Page meta info (language-dependent)', 'verbose_name_plural': 'Page meta info (language-dependent)'},
        ),
        migrations.AlterModelOptions(
            name='pagemeta',
            options={'verbose_name': 'Page meta info (all languages)', 'verbose_name_plural': 'Page meta info (all languages)'},
        ),
        migrations.AlterModelOptions(
            name='titlemeta',
            options={'verbose_name': 'Page meta info (language-dependent)', 'verbose_name_plural': 'Page meta info (language-dependent)'},
        ),
        migrations.AlterField(
            model_name='genericmetaattribute',
            name='attribute',
            field=models.CharField(blank=True, default='', help_text='Custom attribute', max_length=200, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='genericmetaattribute',
            name='name',
            field=models.CharField(help_text='Meta attribute name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genericmetaattribute',
            name='value',
            field=models.CharField(help_text='Meta attribute value', max_length=2000, verbose_name='value'),
        ),
    ]
