# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0007_auto_20160530_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericmetaattribute',
            unique_together=set([]),
        ),
    ]
