# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0007_auto_20160530_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmetaattribute',
            name='value',
            field=models.TextField(help_text='Meta attribute value', verbose_name='value'),
        ),
    ]
