# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0008_auto_20160609_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='twitter_site',
            field=models.CharField(blank=True, default='', help_text="'@' character not required.", max_length=255, verbose_name='Website Twitter Account'),
        ),
    ]
