# Generated by Django 4.2.4 on 2023-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_page_meta", "0013_auto_20200821_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagemeta",
            name="robots",
            field=models.CharField(blank=True, max_length=512, verbose_name="Robots meta tag"),
        ),
        migrations.AlterField(
            model_name="genericmetaattribute",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="pagemeta",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="titlemeta",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
