# Generated by Django 2.2 on 2020-04-24 14:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0013_auto_20200821_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemeta',
            name='robots',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('none', 'none'), ('noindex', 'noindex'), ('noimageindex', 'noimageindex'), ('nofollow', 'nofollow'), ('nosnippet', 'nosnippet'), ('noarchive', 'noarchive'), ('notranslate', 'notranslate')], max_length=255),
        ),
    ]
