# Generated by Django 4.2.4 on 2023-08-30 08:06

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filer", "0017_image__transparent"),
        ("djangocms_page_meta", "0014_pagemeta_robots_alter_genericmetaattribute_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultMetaImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    filer.fields.file.FilerFileField(
                        blank=True,
                        help_text="Default image for og:image, twitter:image and schema.org image."
                        "\nYou can override this by setting the image in Meta-information page extension.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="djangocms_page_meta_default_image",
                        to="filer.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default meta image",
                "verbose_name_plural": "Default meta images",
            },
        ),
    ]
