# Generated by Django 4.2.4 on 2023-08-30 08:07

from django.db import migrations


def generate_default_meta_image_singleton(apps, schema_editor):
    DefaultMetaImage = apps.get_model("djangocms_page_meta", "DefaultMetaImage")
    DefaultMetaImage.objects.create()


def backwards(apps, schema_editor):
    DefaultMetaImage = apps.get_model("djangocms_page_meta", "DefaultMetaImage")
    DefaultMetaImage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_page_meta", "0015_defaultmetaimage"),
    ]

    operations = [
        migrations.RunPython(generate_default_meta_image_singleton, backwards),
    ]
